name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

  sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SAST (ESLint)
        run: npm run lint

  dast:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OWASP ZAP
        run: sudo apt-get install zaproxy

      - name: Run DAST (OWASP ZAP)
        run: |
          zap-cli start
          zap-cli open-url http://localhost:3000 # Adjust based on your application
          zap-cli spider http://localhost:3000
          zap-cli active-scan http://localhost:3000
          zap-cli alerts -l High

      - name: Stop OWASP ZAP
        run: zap-cli shutdown
